[package]
name = "wasmtime-bus-error"
version = "0.1.0"
authors = ["Taylor Thomas <taylor.thomas@microsoft.com>"]
edition = "2018"

[dependencies]
wasmtime = "0.11"
wasmtime-wasi = "0.11"
wasi-common = "0.11"
wasmtime-interface-types = "0.11"
tempfile = "3.1"
wat = "1.0"
wascc-host = "0.2.0"
